name = "thgGradientCurve"
version = "0.1.0"
defaultTargets = ["THGGradient", "THGGradientChallenge", "THGGradientSolution"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "a98628e16c11f5167f16124105ddce53efa9bfe5"

[[lean_lib]]
name = "THGGradient"

[[lean_lib]]
name = "THGGradientChallenge"

[[lean_lib]]
name = "THGGradientSolution"
